# Introduction to Numpy
Learning Numpy

In [2]:
import numpy as np
np.__version__

'1.20.3'

## Difference Between Lists and Numpy Arrays
- An array must have elements of the same type, unlike a list
- An array size is immutable

In [4]:
gpas_as_list = [4.0, 3.286, 3.5]

In [5]:
#Can have elements appeneded to it
gpas_as_list.append(4.0)
#Can have multiple datatypes in it
gpas_as_list.insert(1, 'Whatevs')
#Can have items removed
gpas_as_list.pop(1)

'Whatevs'

In [6]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0]

In [7]:
#Create a numpy array
gpas = np.array(gpas_as_list)

In [9]:
gpas.dtype

dtype('float64')

In [10]:
gpas.itemsize

8

In [11]:
gpas.size

4

In [12]:
len(gpas)

4

In [13]:
gpas.nbytes

32

In [19]:
study_minutes = np.zeros(100,  np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [20]:
%whos

Variable            Type       Data/Info
----------------------------------------
first_day_minutes   uint16     150
np                  module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
study_minutes       ndarray    100: 100 elems, type `uint16`, 200 bytes


In [8]:
study_minutes[0] = 150

In [9]:
first_day_minutes = study_minutes[0]

In [10]:
first_day_minutes

150

In [11]:
type(first_day_minutes)

numpy.uint16

In [12]:
study_minutes[1] = 60

In [13]:
study_minutes

array([150,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [15]:
study_minutes[2:6] = [80, 60, 30, 90]

In [16]:
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [24]:
students_gpas = np.array([
                          [4.0, 3.286, 3.5, 4.0],
                          [3.2, 3.8, 4.0, 4.0],
                          [3.96, 3.92, 4.0, 4.0]
                         ], np.float16)

In [27]:
students_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [28]:
#number of dimensions
students_gpas.ndim

2

In [29]:
# 3 rows by 4 columns
students_gpas.shape

(3, 4)

In [30]:
students_gpas.size

12

In [32]:
len(students_gpas)

3

In [33]:
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x5568314fbdf0
byteorder:  little
byteswap:  False
type: float16


In [34]:
#obtain row
students_gpas[2]

array([3.96, 3.92, 4.  , 4.  ], dtype=float16)

In [35]:
#get single record
students_gpas[2][3]

4.0

NameError: name 'rank' is not defined