# Introduction to Numpy
Learning Numpy

In [1]:
import numpy as np
np.__version__

'1.21.2'

## Difference Between Lists and Numpy Arrays
- An array must have elements of the same type, unlike a list
- An array size is immutable

In [2]:
gpas_as_list = [4.0, 3.286, 3.5]

In [3]:
#Can have elements appeneded to it
gpas_as_list.append(4.0)
#Can have multiple datatypes in it
gpas_as_list.insert(1, 'Whatevs')
#Can have items removed
gpas_as_list.pop(1)

'Whatevs'

In [4]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0]

In [5]:
#Create a numpy array
gpas = np.array(gpas_as_list)

In [6]:
gpas.dtype

dtype('float64')

In [7]:
gpas.itemsize

8

In [8]:
gpas.size

4

In [9]:
len(gpas)

4

In [10]:
gpas.nbytes

32

In [11]:
study_minutes = np.zeros(100,  np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [12]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [13]:
study_minutes[0] = 150

In [14]:
first_day_minutes = study_minutes[0]

In [15]:
first_day_minutes

150

In [16]:
type(first_day_minutes)

numpy.uint16

In [17]:
study_minutes[1] = 60

In [18]:
study_minutes

array([150,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [19]:
study_minutes[2:6] = [80, 60, 30, 90]

In [20]:
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [21]:
students_gpas = np.array([
                          [4.0, 3.286, 3.5, 4.0],
                          [3.2, 3.8, 4.0, 4.0],
                          [3.96, 3.92, 4.0, 4.0]
                         ], np.float16)

In [22]:
students_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [23]:
#number of dimensions
students_gpas.ndim

2

In [24]:
# 3 rows by 4 columns
students_gpas.shape

(3, 4)

In [25]:
students_gpas.size

12

In [26]:
len(students_gpas)

3

In [27]:
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0xed4660
byteorder:  little
byteswap:  False
type: float16


In [28]:
#obtain row
students_gpas[2]

array([3.96, 3.92, 4.  , 4.  ], dtype=float16)

In [29]:
#get single record
students_gpas[2][3]

4.0

In [30]:
study_minutes = np.array([
        
    study_minutes,
    np.zeros(100, np.uint16)
])

In [31]:
study_minutes.shape

(2, 100)

In [34]:
#SetRound2 day 1 to 60
study_minutes[1][0] = 60

In [38]:
#Can put a comma instead of two brackets
study_minutes[1,0]

60

In [42]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size = 100, dtype = np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [43]:
[fake_log[3], fake_log[8]]

[44, 50]

In [46]:
fake_log[[3,8]]

array([44, 50], dtype=uint16)

In [48]:
index = np.array([
    [3, 8],
    [0, 1]
])

fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [51]:
study_minutes = np.append(study_minutes, [fake_log], axis = 0)
study_minutes.shape

(5, 100)

In [59]:
study_minutes[1,1] = 360

In [61]:
#compares every value
fake_log[fake_log <60]


array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [62]:
results = []
for value in fake_log:
    if value <60:
        results.append(value)
np.array(results)
        

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [63]:
np.array([False, True, True]) & np.array([True, False, True])

array([False, False,  True])

In [65]:
study_minutes[(study_minutes < 60) & (study_minutes >0)]

array([30, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52,
       31, 57, 37, 58, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47,
       43, 38, 52, 31, 57, 37, 58, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31,
       59, 50, 47, 43, 38, 52, 31, 57, 37, 58], dtype=uint16)

In [66]:
study_minutes[(study_minutes < 60)] =0

In [68]:
study_minutes[2]

array([132, 122, 128,   0, 136, 129, 101,  95,   0, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
         0, 106, 117,   0,  98,  67, 121, 159,  81, 170,   0,   0,   0,
        87, 179,   0, 116, 177, 118,  78, 171, 117,  88, 123, 102,   0,
        79,   0, 108,  80,   0, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,   0, 102, 113,   0, 131, 161, 118,  82,  89,  81,   0,
        81,   0, 119,   0,  82,   0, 159,   0, 113,  71, 121, 140,  91,
        70,   0, 106,  64, 127, 110,   0,  93,  79], dtype=uint16)

## Boolean Array Indexing
* You can create a boolean array by using comparison operators on an array.
  * You can use boolean arrays for fancy indexing.
  * Boolean arrays can be compared by using bitwise operators (`&`, `|`)
      * Do not use the `and` keyword.
      * Remember to mind the order of operations when combining
* Even though boolean indexing returns a new array, you can update an existing array using a boolean index.

In [69]:
fruit = ["apple", "banana", "cherry", "durian"]

In [71]:
fruit[1:3]

['banana', 'cherry']

In [72]:
fruit[:3]

['apple', 'banana', 'cherry']

In [73]:
fruit[3:]

['durian']

In [74]:
fruit[:]

['apple', 'banana', 'cherry', 'durian']

In [75]:
copied = fruit[:]

In [77]:
copied[3] = "cheese"
#Slicing a list returns a copy

In [78]:
fruit, copied

(['apple', 'banana', 'cherry', 'durian'],
 ['apple', 'banana', 'cherry', 'cheese'])

In [81]:
fruit[::2]

['apple', 'cherry']

In [82]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
practice = np.arange(42)
practice.shape = (7,6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [92]:
practice[2:5, 3::2]

array([[15, 17],
       [21, 23],
       [27, 29]])

In [95]:
#slices don't return a copy, but a view in the data
not_copied = practice[:]
not_copied[0,0] = 90210
practice, not_copied

(array([[90210,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[90210,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [99]:
practice.base is None

True

In [100]:
not_copied.base is None

False

In [101]:
high_scores = np.array(
    [1247700, 1234200, 1218000, 1206800, 1143100]
)


In [104]:
first_couple = high_scores[:2]
first_couple[0] = 8675309
high_scores[0]

8675309

## Slicing
* Works a lot like normal list slicing.
* You can use commas to separate each dimension slice.
* Always returns a data view
* You can access the base object using the `ndarray.base` property


In [106]:
practice_view = practice.reshape(3,14)
practice, practice_view, practice_view.base is practice

(array([[90210,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[90210,     1,     2,     3,     4,     5,     6,     7,     8,
             9,    10,    11,    12,    13],
        [   14,    15,    16,    17,    18,    19,    20,    21,    22,
            23,    24,    25,    26,    27],
        [   28,    29,    30,    31,    32,    33,    34,    35,    36,
            37,    38,    39,    40,    41]]),
 True)

In [108]:
practice.reshape(-1,2).shape

(21, 2)

In [109]:
practice.ravel()

array([90210,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41])

In [111]:
#Look for Numpy documentation
np.lookfor("ravel")

Search results for 'ravel'
--------------------------
numpy.extract
    Return the elements of an array that satisfy some condition.
numpy.unravel_index
    Converts a flat index or array of flat indices into a tuple
numpy.ma.ravel
    Returns a 1D version of self, as a view.
numpy.Bytes0.ravel
    Scalar method identical to the corresponding array attribute.
numpy.flatnonzero
    Return indices that are non-zero in the flattened version of a.
numpy.ravel_multi_index
    Converts a tuple of index arrays into an array of flat
numpy.matrix.ravel
    Return a flattened matrix.
numpy.chararray.ravel
    a.ravel([order])
numpy.matrix.getA1
    Return `self` as a flattened `ndarray`.
numpy.ravel
    Return a contiguous flattened array.
numpy.core._multiarray_umath.unravel_index
    Converts a flat index or array of flat indices into a tuple
numpy.core._multiarray_umath.ravel_multi_index
    Converts a tuple of index arrays into an array of flat
numpy.outer
    Compute the outer product of tw